# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 382d084810e004b6cbeeff3bab192e5d9768cbb079cb99a8160ad614afb68495adedbeff84439dd13349a4e71079a661c4d15e3444c34b8f6be76c070be11b24

test:
  secret_key_base: e1941ad94fcd01153035c3240d85fca9d6663157c094dc563389b288d04db79fc3688a3b76cd48aae262896168aee5603b8f1cc6d9a2c7f77c3416ba4c952218

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
